/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/py/generate-gene-structure-svg": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Gene Structure Svg
     * @description フロントエンドから送られたGeneStructureInfoを基に遺伝子構造を描画するエンドポイント
     */
    post: operations["generate_gene_structure_svg_api_py_generate_gene_structure_svg_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root */
    get: operations["root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** DrawSettings */
    DrawSettings: {
      /** Mode */
      mode: string;
      /** Utr Color */
      utr_color: string;
      /** Exon Color */
      exon_color: string;
      /** Line Color */
      line_color: string;
      /** Intron Shape */
      intron_shape: string;
      /** Gene Height */
      gene_height?: number | null;
      /** Margin X */
      margin_x?: number | null;
      /** Margin Y */
      margin_y?: number | null;
    };
    /** GeneStructureInfo */
    GeneStructureInfo: {
      /** Seq Id */
      seq_id?: string | null;
      /** Source */
      source?: string | null;
      /** Type */
      type?: string | null;
      /** Start */
      start?: number | null;
      /** End */
      end?: number | null;
      /** Score */
      score?: number | null;
      /** Strand */
      strand?: string | null;
      /** Phase */
      phase?: string | null;
      /** Attributes */
      attributes?: Record<string, never> | null;
      /** Transcript Id */
      transcript_id: string;
      /** Total Length */
      total_length: number;
      /** Exons */
      exons: components["schemas"]["Position"][];
      /** Cds */
      cds: components["schemas"]["Position"][];
      /** Five Prime Utrs */
      five_prime_utrs: components["schemas"]["Position"][];
      /** Three Prime Utrs */
      three_prime_utrs: components["schemas"]["Position"][];
    };
    /** GeneStructureRequest */
    GeneStructureRequest: {
      draw_settings: components["schemas"]["DrawSettings"];
      gene_structure: components["schemas"]["GeneStructureInfo"];
      /**
       * Deletion Regions
       * @default []
       */
      deletion_regions: number[][];
      /**
       * Domains
       * @default []
       */
      domains: Record<string, never>[];
      /** Protein Domain Start */
      protein_domain_start?: number | null;
      /** Protein Domain End */
      protein_domain_end?: number | null;
      /** Protein Domain Name */
      protein_domain_name?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Position */
    Position: {
      /** Start */
      start: number;
      /** End */
      end: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  generate_gene_structure_svg_api_py_generate_gene_structure_svg_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeneStructureRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
